services:
  - type: web
    name: 68gb-game-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: singapore
    branch: main
    healthCheckPath: /health
    envVars:
      - key: DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        value: sqlite:///./data/game_data.db
      - key: GAME_URL
        value: https://68gbvn25.biz/
      - key: CRAWL_INTERVAL
        value: 30
      - key: MAX_RETRIES
        value: 3
      - key: REQUEST_TIMEOUT
        value: 30
      - key: HEADLESS_BROWSER
        value: true
      - key: BROWSER_TIMEOUT
        value: 30
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FILE
        value: logs/app.log
      - key: SECRET_KEY
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: EMAIL_SMTP_SERVER
        sync: false
      - key: EMAIL_SMTP_PORT
        value: 587
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
